name = "Mysia's Create Pack 1.19.2 Forge"
author = "Teuthras"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cce0d8c44d4fc379abc5a6ecad344d64688af870b454f5d1a075193e8f282a62"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
