name = "Mysia's Create Pack 1.19.2 Forge"
author = "Teuthras"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81c4295d0c949e4bd95667931a098a1d06f8f1e4a20224c9ce9d096ff43b45c3"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
